SchoolExamGuide.UI/Controllers/ClassMasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchoolExamGuide.BL;
using SchoolExamGuide.Entities;
using System.Net.Http.Headers;

namespace SchoolExamGuide.UI.Controllers
{
    public class ClassMasterController : Controller
    {
        // GET: ClassMaster
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SaveUpdateClassMaster(ClassMasterEntity classMaster)
        {
            ClassMasterBL classMasterBl = new ClassMasterBL();
            int rowAffected = classMasterBl.SaveUpdateClassMaster(classMaster);
            return Json(rowAffected, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DeleteClassMaster(int ID)
        {
            ClassMasterBL classMasterBl = new ClassMasterBL();
            int rowAffected = classMasterBl.DeleteClassMaster(ID);
            return Json(rowAffected, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetClassMasterDetailsByID(int ID)
        {
            ClassMasterBL classMasterBl = new ClassMasterBL();
            return Json(classMasterBl.GetClassMasterDetailsByID(ID), JsonRequestBehavior.AllowGet);
        }

        public JsonResult LoadClassMasterPageWise()
        {
            int draw, start, length;
            int pageIndex = 0;

            if (null != Request.Form.GetValues("draw"))
            {
                draw = int.Parse(Request.Form.GetValues("draw").FirstOrDefault().ToString());
                start = int.Parse(Request.Form.GetValues("start").FirstOrDefault().ToString());
                length = int.Parse(Request.Form.GetValues("length").FirstOrDefault().ToString());
            }
            else
            {
                draw = 1;
                start = 0;
                length = 50;
            }

            if (start == 0)
            {
                pageIndex = 1;
            }
            else
            {
                pageIndex = (start / length) + 1;
            }

            ClassMasterBL classMasterBl = new ClassMasterBL();
            int totalrecords = 0;

            List<ClassMasterEntity> list = new List<ClassMasterEntity>();
            list = classMasterBl.GetClassMasterDetailsPagewise(pageIndex, ref totalrecords, length);

            var data = list;
            return Json(new { draw = draw, recordsFiltered = totalrecords, recordsTotal = totalrecords, data = data }, JsonRequestBehavior.AllowGet);
        }

    }
}

SchoolExamGuide.UI/Views/ClassMaster/Index.cshtml
@model SchoolExamGuide.Entities.ClassMasterEntity

@{
    ViewBag.Title = "Class";
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/ClassMaster.js"></script>

<body style="background-image: url(../background/depart.jpg);
    background-size: cover;">

    @Html.Hidden("SaveUpdateClassMaster", @Url.Action("SaveUpdateClassMaster", "ClassMaster"))
    @Html.Hidden("loaddata", @Url.Action("LoadClassMasterPageWise", "ClassMaster"))
    @Html.Hidden("deleteClassMaster", @Url.Action("DeleteClassMaster", "ClassMaster"))
    @Html.Hidden("getClassMasterByID", @Url.Action("GetClassMasterDetailsByID", "ClassMaster"))


    <div class="row" style="height:2050px;">
        <div class="col-md-7 bac" style=" width: 100%;">
            <div class="row">
                <div class="col-lg-12">
                    <div class="text m-t-lg">
                        <h2>
                            Class
                        </h2>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-8" style="width: 100%;">

            <div style="height:900px;">
                @*/////////////////////// class="table-responsive"///////////////////////////*@
                <div class="card">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <div class="panel-title"><h4>  </h4></div>
                                </div>
                                <div class="ibox float-e-margins">
                                    <div class="ibox-content">
                                        <form class="form-horizontal" id="MyForm" data-parsley-validate="" novalidate="" action="#">

                                            <div class="panel-heading">
                                            </div>

                                       

                                            <legend></legend>

                                            <div class="form-group" style="margin-right: -600px;">
                                                <label class="col-sm-2 control-label">Class:<font color=""></font> </label>
                                                <div class="col-sm-10" style="width: 30%;">
                                                    <input type="text" class="form-control" style="width: 90%;" id="ClassName" placeholder="Class">
                                                </div>
                                            </div>
                                        
                                           
                                         

                                            <div class="form-group">
                                                <input type="hidden" id="ID" />
                                            </div>

                                            <div class="panel-footer text-center">
                                                <button type="button" class="btn btn-primary" id="btnSave" onclick="return Add();">Save</button>
                                                <button type="button" class="btn btn-primary" id="btnClear" onclick="clearTextBox();">Clear</button>
                                            </div>
                                        </form>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                    @*GRD-Table*@
                    <div style="width: 100%;">
                        <div class="panel panel-default">
                            <div class="card">
                                <div style="width:95%; margin:0 auto" class="tablecontainer">

                                    <input type="hidden" id="hdncount" />
                                    <input type="hidden" id="hdnrole" />
                                    <input type="hidden" id="hdndbfilePath" />


                                    <div class="table-responsive">
                                        @*/////////////////////// class="table-responsive"///////////////////////////*@
                                        <h2>
                                            Student Contact List
                                        </h2>
                                        <table id="ClassMasterTable" class="table table-striped table-bordered table-hover" cellspacing="0" style="width: 93.667%;">
                                            <thead>
                                                <tr>
                                                    <th>Class</th>
                                                    <th>Edit</th>
                                                    <th>Delete</th>
                                                </tr>
                                            </thead>
                                        </table>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        @*/////////////////////// class="table-responsive"///////////////////////////*@

    </div>
</body>

@section Styles {
    @Styles.Render("~/bundles/datatablesCss")
    @Styles.Render("~/bundles/SweetAlertCss")

    @Styles.Render("~/bundles/tagsinputCss")
    @Styles.Render("~/bundles/sliderCtrlCss")
    @Styles.Render("~/bundles/chosenCss")
    @Styles.Render("~/bundles/datetimePickerCss")
    @Styles.Render("~/bundles/ColorPickerCss")
    @Styles.Render("~/bundles/select2Css")
    @Styles.Render("~/bundles/fileUploadCss")

}
@section Scripts {

    @Scripts.Render("~/bundles/datatables")
    @Scripts.Render("~/bundles/demoDatatable")

    @Scripts.Render("~/bundles/parsley")
    @Scripts.Render("~/bundles/SweetAlert")

    @Scripts.Render("~/bundles/filestyle")
    @Scripts.Render("~/bundles/tagsinput")
    @Scripts.Render("~/bundles/chosen")
    @Scripts.Render("~/bundles/sliderCtrl")
    @Scripts.Render("~/bundles/inputmask")
    @Scripts.Render("~/bundles/wysiwyg")
    @Scripts.Render("~/bundles/moment")
    @Scripts.Render("~/bundles/datetimePicker")
    @Scripts.Render("~/bundles/ColorPicker")
    @Scripts.Render("~/bundles/demoForms")
    @Scripts.Render("~/bundles/select2")

    @Scripts.Render("~/bundles/fileUpload")
    @Scripts.Render("~/bundles/demoUpload")

}

<script type="text/javascript">
    $(document).ready(function () {
        SetUpGrid();

    });
</script>